//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagement.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactDBEntities : DbContext
    {
        public ContactDBEntities()
            : base("ContactDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ContactDetail>().HasRequired(contact => contact.Company)
                                   .WithRequiredPrincipal();

   
            base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ContactDetail> ContactDetails { get; set; }
    }
}
